image: maven:latest

stages:
  - build
  - run

#variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean install

run:
  stage: run
  script:
#    - mvn $MAVEN_CLI_OPTS package
#    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.example.app.App"
    - docker build -t springboot-kuber dockerfiles/
    - docker tag springboot-kuber my-registry:8080/hello
    - docker push my-registry:5000/hello