apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  name: springboot-kuber-git
  namespace: default
spec:

  # Insert ssh-keys for allowing users to git push
  authorizedKeys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDinKMXQymm6EjZMS3z9e08K/ayfRC4gBpiIBQANeg4yZ6RuwxWnot/FA7AuRtIePipRgLNIzy1qUMWWJUcFtcSjbsMcPUG/p4L6e6s/r/zldV79jZgjwnWRBRZiiOxzHT3g7+XCYkSi2kMMnZK7E0kKDgqH/hd7L9wDTUzwcTYPd1vaEpYelv3Vm1Kh8/7/xbh90tH8cVJF3QZsLZz/zfp388pc/riAt1Pp4GoIAlv6sR9NoV1YDpbkhYQTzsQcWGFHjrx/8qvcbdqcsP3ZCrjJgAicRgf2l2ZrgyN+uQz4HSPiZ7IfrjysoMoSbgPCp1rlJCRXeYx8jwnxyQNrs3t"

  # Provide registry details: https://github.com/hasura/gitkube/blob/master/docs/registry.md
  registry:
    url: "docker.io/samukadocker"
    credentials:
      secretRef: springboot-kuber                # Name of docker-registry secret

  # Define deployment rules
  deployments:
    - name: springboot-kuber-git                             # Name of K8s deployment which is updated on git push
      containers:
        - name: echobot                           # Name of container in the deployment which is built during git push
          path: ./                  # Docker build context path in the git repo
          dockerfile: Dockerfile  # Location of Dockerfile for the source code